const OFFICIAL_GAME_SITES: Record<string, string> = {
  'counter-strike-2': 'https://www.counter-strike.net/cs2',
  'dota-2': 'https://www.dota2.com/',
  'pubg-battlegrounds': 'https://pubg.com/',
  'apex-legends': 'https://www.ea.com/games/apex-legends',
  'grand-theft-auto-v-legacy': 'https://www.rockstargames.com/gta-v',
  rust: 'https://rust.facepunch.com/',
  warframe: 'https://www.warframe.com/',
  'destiny-2': 'https://www.bungie.net/7/en/Destiny',
  'team-fortress-2': 'https://www.teamfortress.com/',
  'war-thunder': 'https://warthunder.com/',
  'baldur-s-gate-3': 'https://baldursgate3.game/',
  'elden-ring': 'https://en.bandainamcoent.eu/elden-ring/elden-ring',
  'cyberpunk-2077': 'https://www.cyberpunk.net/',
  'red-dead-redemption-2': 'https://www.rockstargames.com/reddeadredemption2',
  'the-witcher-3-wild-hunt': 'https://www.thewitcher.com/en/witcher3',
  'hogwarts-legacy': 'https://www.hogwartslegacy.com/',
  palworld: 'https://www.pocketpair.jp/palworld',
  'helldivers-2': 'https://www.playstation.com/en-us/games/helldivers-2/',
  'black-myth-wukong': 'https://www.heishenhua.com/',
  'monster-hunter-world': 'https://www.monsterhunterworld.com/',
  'monster-hunter-rise': 'https://www.monsterhunter.com/rise/',
  'stardew-valley': 'https://www.stardewvalley.net/',
  terraria: 'https://terraria.org/',
  valheim: 'https://www.valheimgame.com/',
  hades: 'https://www.supergiantgames.com/games/hades/',
  'hades-ii': 'https://www.supergiantgames.com/games/hades-ii/',
  'dead-cells': 'https://dead-cells.com/',
  'hollow-knight': 'https://www.hollowknight.com/',
  cuphead: 'https://cupheadgame.com/',
  celeste: 'https://www.celestegame.com/',
  'slay-the-spire': 'https://www.megacrit.com/',
  balatro: 'https://www.playbalatro.com/',
  'vampire-survivors': 'https://poncle.games/vampire-survivors/',
  'deep-rock-galactic': 'https://www.deeprockgalactic.com/',
  'no-man-s-sky': 'https://www.nomanssky.com/',
  'sea-of-thieves': 'https://www.seaofthieves.com/',
  'forza-horizon-5': 'https://forza.net/horizon',
  'microsoft-flight-simulator-40th-anniversary': 'https://www.flightsimulator.com/',
  'assetto-corsa': 'https://assettocorsa.gg/',
  'euro-truck-simulator-2': 'https://eurotrucksimulator2.com/',
  'american-truck-simulator': 'https://americantrucksimulator.com/',
  'cities-skylines': 'https://www.paradoxinteractive.com/games/cities-skylines/about',
  'cities-skylines-ii': 'https://www.paradoxinteractive.com/games/cities-skylines-ii/about',
  'sid-meier-s-civilization-vi': 'https://civilization.2k.com/civ-vi/',
  rimworld: 'https://rimworldgame.com/',
  factorio: 'https://www.factorio.com/',
  satisfactory: 'https://www.satisfactorygame.com/',
  'dyson-sphere-program': 'https://dysonsphereprogram.com/',
  'crusader-kings-iii': 'https://www.crusaderkings.com/',
  'hearts-of-iron-iv': 'https://www.paradoxinteractive.com/games/hearts-of-iron-iv/about',
  stellaris: 'https://www.stellarisgame.com/',
  'total-war-warhammer-iii': 'https://totalwarwarhammer.com/',
  'age-of-empires-iv-anniversary-edition': 'https://www.ageofempires.com/games/age-of-empires-iv/',
  'mount-blade-ii-bannerlord': 'https://www.taleworlds.com/en/Games/Bannerlord',
  'project-zomboid': 'https://projectzomboid.com/',
  '7-days-to-die': 'https://7daystodie.com/',
  'the-forest': 'https://endnightgames.com/games/the-forest',
  'sons-of-the-forest': 'https://endnightgames.com/games/sons-of-the-forest',
  subnautica: 'https://unknownworlds.com/subnautica/',
  'subnautica-below-zero': 'https://unknownworlds.com/subnautica/subnautica-below-zero/',
  'ark-survival-evolved': 'https://survivetheark.com/',
  'don-t-starve-together': 'https://www.klei.com/games/dont-starve-together',
  kenshi: 'https://lofigames.com/kenshi/',
  dayz: 'https://dayz.com/',
  'lethal-company': 'https://www.zeekerss.com/',
  phasmophobia: 'https://www.kineticgames.co.uk/phasmophobia',
  'among-us': 'https://www.innersloth.com/games/among-us/',
  'fall-guys': 'https://www.fallguys.com/',
  'tom-clancy-s-rainbow-six-siege': 'https://www.ubisoft.com/game/rainbow-six/siege',
  'the-finals': 'https://www.reachthefinals.com/',
  'overwatch-2': 'https://overwatch.blizzard.com/',
  'path-of-exile': 'https://www.pathofexile.com/',
  'diablo-iv': 'https://diablo4.blizzard.com/',
  'lost-ark': 'https://www.playlostark.com/',
  'new-world-aeternum': 'https://www.newworld.com/',
  'final-fantasy-xiv-online': 'https://www.finalfantasyxiv.com/',
  'the-elder-scrolls-online': 'https://www.elderscrollsonline.com/',
  'black-desert': 'https://www.naeu.playblackdesert.com/',
  'guild-wars-2': 'https://www.guildwars2.com/',
  'naraka-bladepoint': 'https://www.narakathegame.com/',
  'hunt-showdown-1896': 'https://www.huntshowdown.com/',
  'dead-by-daylight': 'https://deadbydaylight.com/',
  'mortal-kombat-1': 'https://www.mortalkombat.com/',
  'street-fighter-6': 'https://www.streetfighter.com/6/',
  'tekken-8': 'https://tekken.com/',
  'guilty-gear-strive': 'https://www.guiltygear.com/ggst/en/',
  'persona-5-royal': 'https://persona.atlus.com/p5r/',
  'persona-3-reload': 'https://persona.atlus.com/p3r/',
  'like-a-dragon-infinite-wealth': 'https://yakuza.sega.com/like-a-dragon-infinite-wealth',
  'yakuza-0': 'https://yakuza.sega.com/yakuza0',
  'nier-automata': 'https://nierautomata.square-enix-games.com/',
  'final-fantasy-vii-remake-intergrade': 'https://ffvii.square-enix-games.com/en-us/games/remake',
  'resident-evil-4': 'https://www.residentevil.com/re4/',
  'resident-evil-village': 'https://www.residentevil.com/village/',
  'resident-evil-2': 'https://www.residentevil2.com/',
  'silent-hill-2': 'https://www.konami.com/games/silenthill/2r/',
  'control-ultimate-edition': 'https://www.remedygames.com/games/control',
  'death-stranding-director-s-cut': 'https://www.kojimaproductions.jp/en/death-stranding-directors-cut',
  'god-of-war': 'https://www.playstation.com/en-us/games/god-of-war/',
  'marvel-s-spider-man-remastered': 'https://www.playstation.com/en-us/games/marvels-spider-man-remastered/',
};

export function officialSiteForSlug(slug: string): string | null {
  return OFFICIAL_GAME_SITES[slug] ?? null;
}

export function isSteamUrl(value: string | null | undefined): boolean {
  if (!value) return false;
  try {
    const host = new URL(value).hostname.toLowerCase();
    return host === 'steampowered.com' || host.endsWith('.steampowered.com');
  } catch {
    return false;
  }
}

export function resolveNonSteamGameUrl(slug: string, rawUrl?: string | null): string {
  const trimmed = rawUrl?.trim();
  if (trimmed && !isSteamUrl(trimmed)) return trimmed;
  return officialSiteForSlug(slug) ?? `/games/${slug}`;
}
